use std::env;
use std::fs::File;
use std::io::Write;
use std::path::PathBuf;

fn main() {
    // Read configuration from environment variables set by CMake
    let default_wifi_ssid = env::var("HHG_DEFAULT_WIFI_SSID").unwrap_or_else(|_| "".to_string());
    let default_wifi_password = env::var("HHG_DEFAULT_WIFI_PASSWORD").unwrap_or_else(|_| "".to_string());
    let default_wifi_hostname = env::var("HHG_DEFAULT_WIFI_HOSTNAME").unwrap_or_else(|_| "hi-happy-garden-rs".to_string());
    let default_wifi_enabled = env::var("HHG_DEFAULT_WIFI_ENABLED").unwrap_or_else(|_| "false".to_string()).parse::<bool>().unwrap_or(false);
    let default_timezone = env::var("HHG_DEFAULT_TIMEZONE").unwrap_or_else(|_| "0".to_string()).parse::<u16>().unwrap_or(60);
    let default_daylight_saving = env::var("HHG_DEFAULT_DAYLIGHT_SAVING").unwrap_or_else(|_| "false".to_string()).parse::<bool>().unwrap_or(true);
    
    // Generate defaults.rs file
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let dest_path = out_dir.join("defaults.rs");
    let mut f = File::create(&dest_path).unwrap();
    
    writeln!(f, "// Auto-generated by build.rs from CMake configuration").unwrap();
    writeln!(f, "").unwrap();
    writeln!(f, "pub const DEFAULT_WIFI_SSID: &str = {};", default_wifi_ssid).unwrap();
    writeln!(f, "pub const DEFAULT_WIFI_PASSWORD: &str = {};", default_wifi_password).unwrap();
    writeln!(f, "pub const DEFAULT_WIFI_HOSTNAME: &str = {};", default_wifi_hostname).unwrap();
    writeln!(f, "pub const DEFAULT_WIFI_ENABLED: bool = {};", default_wifi_enabled).unwrap();
    writeln!(f, "pub const DEFAULT_TIMEZONE: u16 = {};", default_timezone).unwrap();
    writeln!(f, "pub const DEFAULT_DAYLIGHT_SAVING: bool = {};", default_daylight_saving).unwrap();
    
    println!("cargo:rerun-if-env-changed=HHG_DEFAULT_WIFI_SSID");
    println!("cargo:rerun-if-env-changed=HHG_DEFAULT_WIFI_PASSWORD");
    println!("cargo:rerun-if-env-changed=HHG_DEFAULT_WIFI_HOSTNAME");
    println!("cargo:rerun-if-env-changed=HHG_DEFAULT_WIFI_ENABLED");
    println!("cargo:rerun-if-env-changed=HHG_DEFAULT_TIMEZONE");
    println!("cargo:rerun-if-env-changed=HHG_DEFAULT_DAYLIGHT_SAVING");
}
