/***************************************************************************
 *
 * Hi Happy Garden
 * Copyright (C) 2023/2026 Antonio Salsi <passy.linux@zresa.it>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, see <https://www.gnu.org/licenses/>.
 *
 ***************************************************************************/
#![allow(dead_code)]

use alloc::format;
use alloc::string::String;

use cjson_binding::{from_json, to_json};

use osal_rs::os::{RawMutex, RawMutexFn};
use osal_rs::utils::Bytes;
use osal_rs::utils::{Error, Result};
use osal_rs::{log_info, log_warning};

use osal_rs_serde::{Deserialize, Serialize};
use at_parser_rs::at_quoted as quoted;

use crate::apps::parser::{CMD_SIZE, NOT_LOGGED_RESPONSE, at_cmd_response};
use crate::apps::session::Session;
use crate::apps::signals::status::{StatusFlag, StatusSignal};
use crate::drivers::date_time::DateTime;
use crate::drivers::filesystem::{FileBytes, Filesystem, flags};
use crate::drivers::network::Network;
use crate::drivers::platform::{FS_CONFIG_DIR, FS_SEPARATOR_DIR};
use crate::drivers::wifi::{Auth, Wifi};
use crate::traits::signal::Signal;
use crate::traits::state::Initializable;

use at_parser_rs::{AtError, AtResult};
use at_parser_rs::context::AtContext;

// Include default configuration values generated by build.rs from CMake
mod defaults {
    include!(concat!(env!("OUT_DIR"), "/defaults.rs"));
}

use defaults::*;

const APP_TAG: &str = "AppConfig";

static mut MUTEX: Option<RawMutex> = None;

const fn mutex() -> &'static RawMutex {
    unsafe {
        match &*&raw const MUTEX {
            Some(mutex) => mutex,
            None => panic!("MUTEX_HANDLER is not initialized"),
        }
    }
}

static mut CONFIG: Config = Config {
    version: 0,
    serial: Bytes::new(),
    timezone: 0,
    daylight_saving_time: DaylightSavingTime {
        start_month: 3,
        start_day: 0xFF,
        start_hour: 2,
        end_month: 10,
        end_day: 0xFF,
        end_hour: 3,
        enabled: false,
    },
    session: Session::new(),
    wifi: WifiConfig {
        ssid: Bytes::new(),
        password: Bytes::new(),
        auth: Auth::Wpa2,
        enabled: false,
    },
    ntp: NtpConfig {
        server: Bytes::new(),
        port: 123,
        msg_len: 48,
    },
};

#[derive(Serialize, Deserialize, Clone, Copy)]
pub struct DaylightSavingTime {
    pub start_month: u8,
    pub start_day: u8,
    pub start_hour: u8,
    pub end_month: u8,
    pub end_day: u8,
    pub end_hour: u8,
    pub enabled: bool,
}

impl Default for DaylightSavingTime {
    fn default() -> Self {
        Self {
            start_month: DEFAULT_DAYLIGHT_SAVING_START_MONTH,
            start_day: DEFAULT_DAYLIGHT_SAVING_START_DAY,
            start_hour: DEFAULT_DAYLIGHT_SAVING_START_HOUR,
            end_month: DEFAULT_DAYLIGHT_SAVING_END_MONTH,
            end_day: DEFAULT_DAYLIGHT_SAVING_END_DAY,
            end_hour: DEFAULT_DAYLIGHT_SAVING_END_HOUR,
            enabled: DEFAULT_DAYLIGHT_SAVING_ENABLED,
        }
    }
}

impl DaylightSavingTime {
    pub const AT_CMD: &'static str = "AT+DST";
    pub const AT_RESP: &'static str = "+DST: ";
}

impl AtContext<{ CMD_SIZE }> for DaylightSavingTime {
    fn query(&mut self, at_response: &'static str) -> AtResult<'_, { CMD_SIZE }> {
        let mut response = Bytes::<{ CMD_SIZE }>::new();
        response.format(format_args!("{},{},{},{},{},{},{}",
            self.start_month, self.start_day, self.start_hour,
            self.end_month, self.end_day, self.end_hour,
            self.enabled as u8));
        Ok((at_response, response))
    }

    #[inline]
    fn test(&mut self, at_response: &'static str) -> AtResult<'_, { CMD_SIZE }> {
        Ok(at_cmd_response!(at_response; "start_month,<value> | start_day,<value> | start_hour,<value> | end_month,<value> | end_day,<value> | end_hour,<value> | enabled,<0|1>"))
    }

    fn set(&mut self, at_response: &'static str, args: at_parser_rs::Args) -> AtResult<'_, { CMD_SIZE }> {
        if StatusSignal::get() & <StatusFlag as Into<u32>>::into(StatusFlag::UserLogged) == 0 {
            return Err((at_response, AtError::Unhandled(NOT_LOGGED_RESPONSE)));
        }
        let cmd = args.get(0).ok_or((at_response, AtError::InvalidArgs))?;
        match cmd.as_ref() {
            "start_month" => 
                self.start_month = args.get(1).ok_or((at_response, AtError::InvalidArgs))?
                    .parse().map_err(|_| (at_response, AtError::InvalidArgs))?,
            
            "start_day" => 
                self.start_day = args.get(1).ok_or((at_response, AtError::InvalidArgs))?
                    .parse().map_err(|_| (at_response, AtError::InvalidArgs))?,

            "start_hour" => 
                self.start_hour = args.get(1).ok_or((at_response, AtError::InvalidArgs))?
                    .parse().map_err(|_| (at_response, AtError::InvalidArgs))?,

            "end_month" => 
                self.end_month = args.get(1).ok_or((at_response, AtError::InvalidArgs))?
                    .parse().map_err(|_| (at_response, AtError::InvalidArgs))?,

            "end_day" => 
                self.end_day = args.get(1).ok_or((at_response, AtError::InvalidArgs))?
                    .parse().map_err(|_| (at_response, AtError::InvalidArgs))?,
            
            "end_hour" => 
                self.end_hour = args.get(1).ok_or((at_response, AtError::InvalidArgs))?
                    .parse().map_err(|_| (at_response, AtError::InvalidArgs))?,
            
            "enabled" => {
                let value: u8 = args.get(1).ok_or((at_response, AtError::InvalidArgs))?
                    .parse().map_err(|_| (at_response, AtError::InvalidArgs))?;
                self.enabled = value != 0;
            }
            _ => return Err((at_response, AtError::InvalidArgs)),
        }

        Config::shared().apply_daylight_saving_time();

        Ok(at_cmd_response!(at_response; ""))
    }
}

#[derive(Serialize, Deserialize, Clone, Copy)]
pub struct WifiConfig {
    ssid: Bytes<32>,
    password: Bytes<32>,
    auth: Auth,
    enabled: bool,
}

impl Default for WifiConfig {
    fn default() -> Self {
        Self {
            ssid: Bytes::from_str(DEFAULT_WIFI_SSID),
            password: Bytes::from_str(DEFAULT_WIFI_PASSWORD),
            auth: DEFAULT_WIFI_AUTH.into(),
            enabled: DEFAULT_WIFI_ENABLED,
        }
    }
}

impl WifiConfig {
    pub const AT_CMD: &'static str = "AT+WIFI";
    pub const AT_RESP: &'static str = "+WIFI: ";

    pub fn get_ssid(&self) -> &Bytes<32> {
        mutex().lock();
        let ssid = &self.ssid;
        mutex().unlock();
        ssid
    }

    pub fn get_password(&self) -> &Bytes<32> {
        mutex().lock();
        let password = &self.password;
        mutex().unlock();
        password
    }

    pub fn is_enabled(&self) -> bool {
        mutex().lock();
        let enabled = self.enabled;
        mutex().unlock();
        enabled
    }

    pub fn get_auth(&self) -> Auth {
        mutex().lock();
        let auth = self.auth;
        mutex().unlock();
        auth
    }

    pub fn set_ssid(&mut self, ssid: Bytes<32>) {
        mutex().lock();
        self.ssid = ssid;
        mutex().unlock();
    }

    pub fn set_password(&mut self, password: Bytes<32>) {
        mutex().lock();
        self.password = password;
        mutex().unlock();
    }

    pub fn set_enabled(&mut self, enabled: bool) {
        mutex().lock();
        self.enabled = enabled;
        mutex().unlock();
    }

    pub fn set_auth(&mut self, auth: Auth) {
        mutex().lock();
        self.auth = auth;
        mutex().unlock();
    }
}

impl AtContext<{ CMD_SIZE }> for WifiConfig {
    
    #[inline]
    fn query(&mut self, at_response: &'static str) -> AtResult<'_, { CMD_SIZE }> {
        Ok(at_cmd_response!(at_response; quoted!(self.ssid.as_str()), <Auth as Into<u8>>::into(self.auth), self.enabled as u8))
    }

    #[inline]
    fn test(&mut self, at_response: &'static str) -> AtResult<'_, { CMD_SIZE }> {
        Ok(at_cmd_response!(at_response; "<ssid>,<password>,<auth(0-6)>,<enabled(0|1)>"))
    }

    fn set(&mut self, at_response: &'static str, args: at_parser_rs::Args) -> AtResult<'_, { CMD_SIZE }> {
        if StatusSignal::get() & <StatusFlag as Into<u32>>::into(StatusFlag::UserLogged) == 0 {
            return Err((at_response, AtError::Unhandled(NOT_LOGGED_RESPONSE)));
        }
        let ssid = args.get(0).ok_or((at_response, AtError::InvalidArgs))?;
        if ssid.len() > 32 {
            return Err((at_response, AtError::Unhandled("ssid max len 32")));
        }
        let password = args.get(1).ok_or((at_response, AtError::InvalidArgs))?;
        if password.len() > 32 {
            return Err((at_response, AtError::Unhandled("password max len 32")));
        }
        let auth: u8 = args.get(2).ok_or((at_response, AtError::InvalidArgs))?
            .parse().map_err(|_| (at_response, AtError::InvalidArgs))?;
        let enabled: u8 = args.get(3).ok_or((at_response, AtError::InvalidArgs))?
            .parse().map_err(|_| (at_response, AtError::InvalidArgs))?;

        self.ssid = Bytes::from_str(ssid.as_ref());
        self.password = Bytes::from_str(password.as_ref());
        self.auth = Auth::from(auth);
        self.enabled = enabled != 0;

        Config::shared().apply_wifi();

        Ok(at_cmd_response!(at_response; ""))
    }
}

#[derive(Serialize, Deserialize, Clone, Copy)]
pub struct NtpConfig {
    server: Bytes<64>,
    port: u16,
    msg_len: u16,
}

impl Default for NtpConfig {
    fn default() -> Self {
        Self {
            server: Bytes::from_str(DEFAULT_NTP_SERVER),
            port: DEFAULT_NTP_PORT,
            msg_len: DEFAULT_NTP_MSG_LEN,
        }
    }
}

impl NtpConfig {
    pub const AT_CMD: &'static str = "AT+NTP";
    pub const AT_RESP: &'static str = "+NTP: ";

    pub fn get_server(&self) -> &Bytes<64> {
        mutex().lock();
        let server = &self.server;
        mutex().unlock();
        server
    }

    pub fn get_port(&self) -> u16 {
        mutex().lock();
        let port = self.port;
        mutex().unlock();
        port
    }

    pub fn get_msg_len(&self) -> u16 {
        mutex().lock();
        let msg_len = self.msg_len;
        mutex().unlock();
        msg_len
    }

    pub fn set_server(&mut self, server: Bytes<64>) {
        mutex().lock();
        self.server = server;
        mutex().unlock();
    }

    pub fn set_port(&mut self, port: u16) {
        mutex().lock();
        self.port = port;
        mutex().unlock();
    }

    pub fn set_msg_len(&mut self, msg_len: u16) {
        mutex().lock();
        self.msg_len = msg_len;
        mutex().unlock();
    }
}

impl AtContext<{ CMD_SIZE }> for NtpConfig {
    #[inline]
    fn query(&mut self, at_response: &'static str) -> AtResult<'_, { CMD_SIZE }> {
        Ok(at_cmd_response!(at_response; quoted!(self.server.as_str()), self.port, self.msg_len))
    }

    #[inline]
    fn test(&mut self, at_response: &'static str) -> AtResult<'_, { CMD_SIZE }> {
        Ok(at_cmd_response!(at_response; "<server>,<port>,<msg_len>"))
    }

    fn set(&mut self, at_response: &'static str, args: at_parser_rs::Args) -> AtResult<'_, { CMD_SIZE }> {
        if StatusSignal::get() & <StatusFlag as Into<u32>>::into(StatusFlag::UserLogged) == 0 {
            return Err((at_response, AtError::Unhandled(NOT_LOGGED_RESPONSE)));
        }
        let server = args.get(0).ok_or((at_response, AtError::InvalidArgs))?;
        if server.len() > 64 {
            return Err((at_response, AtError::Unhandled("server max len 64")));
        }
        let port: u16 = args.get(1).ok_or((at_response, AtError::InvalidArgs))?
            .parse().map_err(|_| (at_response, AtError::InvalidArgs))?;
        let msg_len: u16 = args.get(2).ok_or((at_response, AtError::InvalidArgs))?
            .parse().map_err(|_| (at_response, AtError::InvalidArgs))?;

        self.server = Bytes::from_str(server.as_ref());
        self.port = port;
        self.msg_len = msg_len;

        Config::shared().apply_ntp();

        Ok(at_cmd_response!(at_response; ""))
    }
}


#[derive(Serialize, Deserialize, Clone, Copy)]
pub struct Config {
    version: u8,
    serial: Bytes<16>,
    timezone: i16,
    daylight_saving_time: DaylightSavingTime,
    session: Session,
    wifi: WifiConfig,
    ntp: NtpConfig,
}

impl Default for Config {
    fn default() -> Self {
        Self {
            version: 0,
            serial: Bytes::new(),
            timezone: DEFAULT_TIMEZONE,
            daylight_saving_time: Default::default(),
            session: Default::default(),
            wifi: Default::default(),
            ntp: Default::default(),
        }
    }
}

impl Initializable for Config {
    fn init(&mut self) -> Result<()> {
        log_info!(APP_TAG, "Init app config");

        unsafe {
            MUTEX = Some(RawMutex::new()?);
        }

        self.session.init()?;

        let config = Self::load()?;
        config.apply_locale();
        config.apply_daylight_saving_time();
        config.apply_ntp();
        config.apply_wifi();
        config.apply_session();


        Ok(())
    }
}

impl AtContext<{ CMD_SIZE }> for Config {
    fn exec(&mut self, at_response: &'static str) -> AtResult<'_, { CMD_SIZE }> {
        Config::save().map_err(|_| (at_response, AtError::Unhandled("Save error")))?;
        Ok(at_cmd_response!(at_response; ""))
    }

    fn query(&mut self, at_response: &'static str) -> AtResult<'_, { CMD_SIZE }> {
        Ok(at_cmd_response!(at_response; quoted!(self.serial.as_str()), self.timezone))
    }

    #[inline]
    fn test(&mut self, at_response: &'static str) -> AtResult<'_, { CMD_SIZE }> {
        Ok(at_cmd_response!(at_response; "serial,<value> | timezone,<value> | save | load"))
    }

    fn set(&mut self, at_response: &'static str, args: at_parser_rs::Args) -> AtResult<'_, { CMD_SIZE }> {
        if StatusSignal::get() & <StatusFlag as Into<u32>>::into(StatusFlag::UserLogged) == 0 {
            return Err((at_response, AtError::Unhandled(NOT_LOGGED_RESPONSE)));
        }
        let cmd = args.get(0).ok_or((at_response, AtError::InvalidArgs))?;
        match cmd.as_ref() {
            "serial" => {
                let value = args.get(1).ok_or((at_response, AtError::InvalidArgs))?;
                if value.len() > 16 {
                    return Err((at_response, AtError::Unhandled("serial max len 16")));
                }
                self.serial = Bytes::from_str(value.as_ref());
            }
            "timezone" => {
                let value: i16 = args.get(1).ok_or((at_response, AtError::InvalidArgs))?
                    .parse().map_err(|_| (at_response, AtError::InvalidArgs))?;
                self.timezone = value;
                self.apply_locale();
            }
            "save" => {
                Config::save().map_err(|_| (at_response, AtError::Unhandled("Save error")))?;
            }
            "load" => {
                let config = Config::load().map_err(|_| (at_response, AtError::Unhandled("Load error")))?;
                config.apply_locale();
                config.apply_daylight_saving_time();
                config.apply_ntp();
                config.apply_wifi();
                config.apply_session();
            }
            _ => return Err((at_response, AtError::InvalidArgs)),
        }
        Ok(at_cmd_response!(at_response; ""))
    }
}

impl Config {
    const FILE_NAME: &'static str = "config.json";
    pub const AT_CMD: &'static str = "AT+CNF";
    pub const AT_RESP: &'static str = "+CNF: ";

    /// Initialize Config with default values from CMake
    fn with_defaults() -> Self {
        let mut config = Self::default();

        // Apply CMake defaults to WiFi config
        config.wifi = Default::default();
        // Apply CMake defaults to general config
        config.timezone = DEFAULT_TIMEZONE;
        config.daylight_saving_time = Default::default();

        // Set system user (position 0) from CMake defaults
        let _ = config.session.set_system_user(DEFAULT_SYSTEM_USER_EMAIL, DEFAULT_SYSTEM_USER_PASSWORD);

        config
    }

    pub fn apply_locale(&self) {
        DateTime::set_timezone(self.timezone);
    }

    pub fn apply_daylight_saving_time(&self) {
        DateTime::set_daylight_saving_time(
            self.daylight_saving_time.enabled,
            self.daylight_saving_time.start_month,
            self.daylight_saving_time.start_day,
            self.daylight_saving_time.start_hour,
            self.daylight_saving_time.end_month,
            self.daylight_saving_time.end_day,
            self.daylight_saving_time.end_hour,
        );
    }

    pub fn apply_ntp(&self) {
        Network::set_ntp(
            self.ntp.get_server().clone(),
            self.ntp.get_port(),
            self.ntp.get_msg_len(),
        );
    }

    pub fn apply_wifi(&self) {
        Wifi::set_config(
            self.wifi.get_ssid().clone(),
            self.wifi.get_password().clone(),
            self.wifi.get_auth(),
            self.wifi.is_enabled(),
        );
    }

    pub fn apply_session(&self) {
        self.session.set_user_local();
    }

    pub const fn shared() -> &'static mut Self {
        unsafe { &mut *&raw mut CONFIG }
    }

    pub fn load() -> Result<&'static mut Self> {
        let mut file_name = FileBytes::from_str(FS_CONFIG_DIR);
        file_name.append_str(FS_SEPARATOR_DIR);
        file_name.append_str(Config::FILE_NAME);

        let mut file = match Filesystem::open_with_as_sync_str(
            &file_name,
            flags::RDWR | flags::CREAT,
        ) {
            Ok(file) => file,
            Err(e @ Error::ReturnWithCode(-2)) => {
                log_info!(APP_TAG, "Failed to open config file: {e}, try to create it");
                Filesystem::open_with_as_sync_str(
                    &file_name,
                    flags::WRONLY | flags::CREAT,
                )?
            }
            Err(e) => return Err(e),
        };

        let wifi_json = file.read_with_as_sync_str(true)?;

        // If file is empty or doesn't exist, use defaults
        if wifi_json.is_empty() {
            log_info!(APP_TAG, "Config file not found or empty, using defaults");

            unsafe {
                CONFIG = Self::with_defaults();
            }

            Self::save()?;

            return Ok(unsafe { &mut *&raw mut CONFIG });
        }

        let wifi_json = match String::from_utf8(wifi_json) {
            Ok(json) => json,
            Err(e) => {
                return Err(Error::UnhandledOwned(format!(
                    "Failed to parse config JSON: {e}"
                )));
            }
        };


        match from_json::<Config>(&wifi_json) {
            Ok(config) => {
                unsafe {
                    CONFIG = config;
                }

                log_info!(APP_TAG, "Config loaded successfully");
                Ok(unsafe { &mut *&raw mut CONFIG })
            }
            Err(e) => {
                log_warning!(APP_TAG, "Using default config values err: {e}");
                unsafe { CONFIG = Self::with_defaults() };

                Self::save()?;

                Ok(unsafe { &mut *&raw mut CONFIG })
            }
        }
    }

    pub fn save() -> Result<&'static mut Self> {
        let mut file_name = FileBytes::from_str(FS_CONFIG_DIR);
        file_name.append_str(FS_SEPARATOR_DIR);
        file_name.append_str(Config::FILE_NAME);

        unsafe {
            to_json(&*&raw const CONFIG)
                .map_err(|e| {
                    Error::UnhandledOwned(format!("Failed to serialize config to JSON: {e}"))
                })
                .and_then(|json| {
                    let json_bytes = json.into_bytes();

                    let mut file = match Filesystem::open_with_as_sync_str(
                        &file_name,
                        flags::WRONLY | flags::CREAT,
                    ) {
                        Ok(file) => file,
                        Err(e @ Error::ReturnWithCode(-2)) => {
                            log_info!(APP_TAG, "Failed to open config file: {e}, try to create it");
                            Filesystem::open_with_as_sync_str(
                                &file_name,
                                flags::WRONLY | flags::CREAT,
                            )?
                        }
                        Err(e) => return Err(e),
                    };

                    file.write(&json_bytes, true)?;

                    log_info!(APP_TAG, "Config saved successfully");
                    Ok(&mut *&raw mut CONFIG)
                })
        }
    }

    pub fn get_version(&self) -> u8 {
        mutex().lock();
        let version = self.version;
        mutex().unlock();
        version
    }

    pub fn get_serial(&self) -> &Bytes<16> {
        mutex().lock();
        let serial = &self.serial;
        mutex().unlock();
        serial
    }

    pub fn set_serial(&mut self, serial: Bytes<16>) {
        mutex().lock();
        self.serial = serial;
        mutex().unlock();
    }

    pub fn get_timezone(&self) -> i16 {
        mutex().lock();
        let timezone = self.timezone;
        mutex().unlock();
        timezone
    }

    pub fn set_timezone(&mut self, timezone: i16) {
        mutex().lock();
        self.timezone = timezone;
        mutex().unlock();
    }

    pub fn get_ntp_config(&self) -> &NtpConfig {
        mutex().lock();
        let ntp = &self.ntp;
        mutex().unlock();
        ntp
    }

    pub fn get_ntp_config_mut(&mut self) -> &mut NtpConfig {
        mutex().lock();
        let ntp = &mut self.ntp;
        mutex().unlock();
        ntp
    }

    pub fn get_daylight_saving_time(&mut self) -> &mut DaylightSavingTime {
        mutex().lock();
        let dst = &mut self.daylight_saving_time;
        mutex().unlock();
        dst
    }

    pub fn get_wifi_config(&mut self) -> &mut WifiConfig {
        mutex().lock();
        let wifi = &mut self.wifi;
        mutex().unlock();
        wifi
    }

    pub fn get_session(&mut self) -> &mut Session {
        mutex().lock();
        let session = &mut self.session;
        mutex().unlock();
        session
    }
}
